name: Build lua-zlib for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Lua
        uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: "5.4" # Укажите версию под вашу систему: 5.1, 5.2, 5.3, 5.4

      - name: Setup LuaRocks
        uses: luarocks/gh-actions-luarocks@v5

      - name: Setup MSYS2 and ZLIB headers
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-zlib

      - name: Build and Pack lua-zlib
        shell: cmd
        run: |
          luarocks build lua-zlib ZLIB_DIR=C:/msys64/mingw64
          luarocks pack lua-zlib

      - name: Upload compiled rock
        uses: actions/upload-artifact@v4
        with:
          name: lua-zlib-windows-x64
          path: "*.rock"
