name: Build lua-zlib for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: "5.4" # При необходимости укажите вашу версию: 5.1, 5.3, 5.4 или luajit

      - name: Setup LuaRocks
        uses: luarocks/gh-actions-luarocks@v5

      - name: Setup MSYS2 (GCC & ZLIB)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-zlib

      - name: Add MinGW to PATH
        shell: cmd
        run: echo C:\msys64\mingw64\bin>>%GITHUB_PATH%

      - name: Build and Pack lua-zlib
        shell: cmd
        run: |
          luarocks build lua-zlib ZLIB_DIR=C:/msys64/mingw64
          luarocks pack lua-zlib

      - name: Upload compiled rock
        uses: actions/upload-artifact@v4
        with:
          name: lua-zlib-windows-x64
          path: "*.rock"
